### ISSUE TITLE
Recipe for "am I being run via a globally activated snapshot?"

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub_cache#16]
Is there a simple way to get this answer?

**Comment by devoncarew** [comment]
Would love to know! I can see a way to detect whether you are run from a dev. environment. If your cwd contains a `pubspec.yaml`, and the `name` property is equal to your app, I think that indicates that you are running in a source checkout of your app.

A local pub run (`pub run`) of an app that is not the one under development (running `packages/grinder` in a foobar project), would have the pubspec be for foobar, not grinder.

A pub global activated app will be run from the user's cwd, and the cwd won't be related to where the app's actual code and assets are. Perhaps we could also use the `Uri.base` property as well? I think for some (all?) pub global activated apps, it's an http: address rather than a file: based one?

The best we may be able to do is infer things for now; not sure what the recipe is though.

**Comment by devoncarew** [comment]
Happy to put the logic in this package, or in a better location, if we can determine a good way to detect the different runtime configurations.

**Comment by sethladd** [comment]
I'm writing it now for dartdoc, would love a review when I'm done.

**Comment by sethladd** [comment]
Here's a shot at it: https://github.com/dart-lang/dartdoc/blob/warning-on-snapshot/lib/resource_loader.dart

Handles loading a package: resource, under the following scenarios:
- Just running via the Dart VM
- Running via pub run + HTTP + source rewriting to HTTP URIs for imports
- Running via snapshot in global_package directory (this was the tough one)

Does not handle:
- Respecting package-root, it currently just looks for a package/ dir in most scenarios
- Probably a billion small details

Would love to discuss this strategy. For now, it might enough until we can load any resource with package: with core SDK capabilities.

**Comment by devoncarew** [comment]
tabling this for now
